markdown: GFM
relative_links: 
  enabled: true
  collections: true
include:
  - README.md
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
- jemoji
- jekyll-mentions
- jekyll-spaceship

